learning_log/learning_log/home/urls.py
from django.conf.urls import url
from django.urls import path
from . import views

urlpatterns = [
    # 主页
    path(r'', views.homepage, name='homepage'),
]

learning_log/learning_log/learning_log/urls.py
from django.contrib import admin
from django.urls import path, include
app_name='[learning_logs]'
urlpatterns = [
    path('admin/', admin.site.urls),
    path('users/', include(('users.urls', 'users'), namespace='users')),
    path('learning_logs/', include(('learning_logs.urls', 'learning_logs'), namespace='learning_logs')),
    path('', include(('home.urls', 'home'), namespace='home'))
]

learning_log/learning_log/learning_logs/urls.py
"""定义learning_logs的url模式"""

from django.conf.urls import url
from django.urls import path
from . import views

urlpatterns = [
    # 主页
    path(r'^index', views.index, name='index'),
    path(r'^topics/', views.topics, name='topics'),
    # 特定页面的详细页面
    path(r'topics/<int:topic_id>/', views.topic, name='topic'),
    # 用于添加新主题的网页
    path(r'^new_topic/$', views.new_topic, name='new_topic'),
    # 用于添加新条目的网页
    path(r'new_entry/(?P<topic_id>\d+)/$', views.new_entry, name='new_entry'),
    # 用于编辑条目的网页
    path(r'edit_entry/<int:entry_id>/$', views.edit_entry, name='edit_entry'),
    # 删除主题
    path(r'delete_topic/<int:topic_id>/$', views.delete_topic, name='delete_topic'),
    # 删除条目
    path(r'delete_entry/<int:entry_id>/$', views.delete_entry, name='delete_entry')
]

learning_log/learning_log/users/urls.py
from django.conf.urls import url
from django.urls import path
from django.contrib.auth.views import LoginView
from . import views

urlpatterns = [
    # 登录页面
    url(r'^login/$', LoginView.as_view(template_name='users/login.html'), name="login"),
    # 注销
    url(r'^logout/$', views.logout_view, name='logout'),
    #注册页面
    url(r'^register/$', views.register, name='register'),
]

learning_log/learning_log/home/models.py
from django.db import models

# Create your models here.

learning_log/learning_log/learning_logs/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.

class Topic(models.Model):
    """用户学习的主题"""
    text = models.CharField(max_length=200)
    date_added = models.DateTimeField(auto_now_add=True)
    owner = models.ForeignKey(User,on_delete=models.CASCADE)

    def __str__(self):
        """返回模型的字符串表示"""
        return self.text

class Entry(models.Model):
    """学到的有关摸个主题的具体指示"""
    topic = models.ForeignKey(Topic, on_delete=models.CASCADE)
    text = models.TextField()
    date_added = models.DateTimeField(auto_now_add=True)

    class Meta:
        verbose_name_plural = 'entries'

    def __str__(self):
        """返回模型的字符串表示"""
        return self.text[:50] + "..."

learning_log/learning_log/users/models.py
from django.db import models

# Create your models here.

learning_log/learning_log/learning_logs/forms.py
from django import forms

from .models import Topic, Entry

class TopicForm(forms.ModelForm):
    class Meta:
        model = Topic
        fields = ['text']
        labels = {'text': ''}

class EntryForm(forms.ModelForm):
    class Meta:
        model = Entry
        fields = ['text']
        labels = {'text': ''}
        widgets = {'text': forms.Textarea(attrs={'cols':80})}

learning_log/learning_log/home/views.py
from django.shortcuts import render
from django.http import HttpResponseRedirect
from django.contrib.auth.decorators import login_required
from django.urls import reverse


# Create your views here.
def homepage(request):
    """网站的首页"""
    return render(request, 'home/homepage.html')

learning_log/learning_log/learning_logs/views.py
from django.shortcuts import render
from django.http import HttpResponseRedirect
from django.contrib.auth.decorators import login_required
from django.urls import reverse

from .models import Topic, Entry
from .forms import TopicForm, EntryForm

# Create your views here.
def index(request):
    """学习笔记的首页"""
    return render(request, 'learning_logs/index.html')

@login_required
def topics(request):
    """显示所有的主题"""
    topics= Topic.objects.filter(owner=request.user).order_by('date_added')
    context = {'topics': topics}
    return render(request, 'learning_logs/topics.html',context)

@login_required
def topic(request, topic_id):
    """显示单个主题及其所有内容"""
    topic = Topic.objects.get(id=topic_id)
    # 确认请求的主题属于当前用户
    if topic.owner != request.user:
        raise Http404
    entries = topic.entry_set.order_by('date_added')
    context = {'topic': topic, 'entries': entries}
    return render(request, 'learning_logs/topic.html',context)

@login_required
def new_topic(request):
    """添加主题"""
    if request.method != 'POST':
        # 未提交数据：创建一个新表单
        form = TopicForm()
    else:
        # POST提交的数据，对数据进行处理
        form = TopicForm(request.POST)
        if form.is_valid():
            new_topic = form.save(commit=False)
            new_topic.owner = request.user
            new_topic.save()
            # HttpResponseRedirect重定向到网页topics
            return HttpResponseRedirect(reverse('learning_logs:topics'))

    context = {'form': form}
    return render(request, 'learning_logs/new_topic.html', context)

@login_required
def new_entry(request, topic_id):
    """在特定的主题中添加条目"""
    topic = Topic.objects.get(id=topic_id)

    if request.method != 'POST':
        # 未提交数据：创建一个新表单
        form = EntryForm()
    else:
        form = EntryForm(data=request.POST)
        # POST提交的数据，对数据进行处理
        form = EntryForm(request.POST)
        if form.is_valid():
            new_entry = form.save(commit=False)
            new_entry.owner = request.user
            new_entry.topic = topic
            new_entry.save()
            # HttpResponseRedirect重定向到网页topics
            return HttpResponseRedirect(reverse('learning_logs:topic',args=[topic_id]))

    context = {'topic': topic, 'form': form}
    return render(request, 'learning_logs/new_entry.html', context)

@login_required
def edit_entry(request, entry_id):
    """编辑既有条目"""
    entry = Entry.objects.get(id=entry_id)
    topic = entry.topic
    # 确认请求的主题属于当前用户
    if topic.owner != request.user:
        raise Http404

    if request.method != 'POST':
        # 初次请求， 使用当前条目填充表单
        form = EntryForm(instance=entry)
    else:
        # 用POST提交的数据，对数据进行处理
        form = EntryForm(instance=entry, data=request.POST)
        if form.is_valid():
            form.save()
            # HttpResponseRedirect重定向到网页topics
            return HttpResponseRedirect(reverse('learning_logs:topic',args=[topic.id]))

    context = {'entry': entry, 'topic': topic, 'form':form}
    return render(request, 'learning_logs/edit_entry.html', context)

@login_required
def delete_topic(request, topic_id):
    """删除既有主题"""
    topic = Topic.objects.get(id=topic_id)
    topic.delete()
    return HttpResponseRedirect(reverse('learning_logs:topics'))

@login_required
def delete_entry(request, entry_id):
    """删除既有条目"""
    entry = Entry.objects.get(id=entry_id)
    topic = entry.topic
    entry.delete()
    return HttpResponseRedirect(reverse('learning_logs:topic', args=[topic.id]))

learning_log/learning_log/users/views.py
from django.shortcuts import render
from django.http import HttpResponseRedirect
from django.urls import reverse
from django.contrib.auth import login,logout, authenticate
from django.shortcuts import render
from django.contrib.auth.forms import UserCreationForm

# Create your views here.
def logout_view(request):
    """注销用户"""
    logout(request)
    return HttpResponseRedirect(reverse('learning_logs:index'))

def register(request):
    """注册新用户"""
    if request.method != 'POST':
        # 显示空的注册表单
        form = UserCreationForm()
    else:
        # 处理填好的表单
        form = UserCreationForm(data=request.POST)
 
    if form.is_valid():
        new_user = form.save()
        #让用户自动登录并重定向到主页
        authenticated_user = authenticate(username=new_user.username, password=request.POST['password1'])
        login(request, authenticated_user)
        return HttpResponseRedirect(reverse('learning_logs:index'))

    context = {'form': form}
    return render(request, 'users/register.html', context)

learning_log/learning_log/home/templates/home/123.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta http-equiv="content-type" content="text/html; charset=utf-8">
    <title>The People's search engine | PeARS</title>
    <link href="https://fonts.googleapis.com/css?family=Rubik:400,400i,500" rel="stylesheet" />
    <link href="styles/website.css" rel="stylesheet" />
    <link href="styles/image.css" rel="stylesheet" />
    <link rel="shortcut icon" href="images/ico/favicon.ico">
    <link rel="apple-touch-icon-precomposed" sizes="144x144" href="images/ico/apple-touch-icon-144-precomposed.png">
    <link rel="apple-touch-icon-precomposed" sizes="114x114" href="images/ico/apple-touch-icon-114-precomposed.png">
    <link rel="apple-touch-icon-precomposed" sizes="72x72" href="images/ico/apple-touch-icon-72-precomposed.png">
    <link rel="apple-touch-icon-precomposed" href="images/ico/apple-touch-icon-57-precomposed.png">
  </head>
  <body>
      <section class="Layout__Sidebar">
        <img class="Logo" src="images/logo.svg" alt="Pearsearch logo"/>
        <nav class="Navigation Navigation--Main">
          <li class="Navigation--Selected"><a href="index.html">Home</a></li>
          <li><a href="technology.html">What is PeARS?</a></li>
          <li><a href="philosophy.html">Philosophy</a></li>
          <li><a href="posts.html">Writing</a></li>
          <li><a href="contribute.html">Contribute</a></li>
          <li><a href="faq.html">F.A.Q.</a></li>
          <li><a href="gallery.html">Gallery</a></li>
          <li><a href="downloads.html">Downloads</a></li>
        </nav>
        <hr class="Navigation__Splitter"/>
        <nav class="Navigation Navigation--Secondry">
          <li><a href="https://github.com/PeARSearch/PeARS-orchard">Install from Github</a></li>
        </nav>
      </section>
      <section class="Layout__Content">

        <h1 class="PageTitle">PeARS: <br/> the people's search engine</h1>

        <section>
        <div><img src="images/snow_pod_frontpage.png" width="600px"/></div><br><br>
        <h2>'We will snow' - join our campaign to index the Web!</h2>
    
        <p>A single snowflake is small, fragile, hardly visible. But taken together, snowflakes can cover entire landscapes, from remote valleys to inaccessible mountain peaks. So it is that many of us, working together, can do what only powerful organisations have achieved so far: explore, search and share the World Wide Web.</p><br>	

        <p>Phase 1 of PeARS, codename 'Orchard', is a decentralised Web search system allowing people to easily <i>index</i> their favourite web pages (i.e. produce a computer-readable, searchable representation of the pages' content). Its main feature is the ability to convert a small index into a greyish, unassuming picture, called a 'snow pod'. Snow pods are the mini-weapons of the indexing revolution. They can easily be shared with others by email, on social media, or through any other mean, so you can be your very own search engine, for yourself and for your friends.</p><br>

        <p>Intrigued? Then <a href="writings/We-will-snow-web-indexing.html">read the whole story</a> or directly find out <a href="writings/Which-web-indexer-are-you.html">which type of Web indexer</a> you are!</p>
       
        </section>

        <ul class="Splitter">
          <li class="Splitter__Square Splitter__Square--small"></li>
          <li class="Splitter__Square Splitter__Square--big"></li>
          <li class="Splitter__Square Splitter__Square--small"></li>
        </ul>


        <div class="CallToAction">
          <a class="Button" href="https://github.com/PeARSearch" target="_blank">
            <img class="Button__Icon" src="images/github-white.svg" alt="github logo"/>
            <span class="Button__Text">Checkout Code</span>
          </a>
          <p class="CallToAction__Hint">join now and start contributing</p>
        </div>

  </body>
</html>

learning_log/learning_log/learning_logs/templates/learning_logs/base.html
{% load bootstrap3 %}

<!DOCTYPE html>
<html lang="en">
  <head>
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <title>Learning Log</title>

    {% bootstrap_css %}
    {% bootstrap_javascript %}
  
  </head>

  <body>

    <!-- Static navbar -->
    <nav class="navbar navbar-default navbar-static-top">
      <div class="container">
          <div class="navbar-header">
            <button type="button" class="navbar-toggle collapsed" 
                data-toggle="collapse" data-target="#navbar"
                aria-expanded="false" aria-controls="navbar">
            </button>
            <a class="navbar-brand" href="{% url 'learning_logs:index' %}">
                Learning Log</a>
          </div>

          <div id="navbar" calss="navbar-collapse collapse">
            <ul class="nav navbar-nav">
              <li><a href="{% url 'learning_logs:topics' %}">Topics</a></li>
            </ul>

            <ul class="nav navbar-nav navbar-right">
              {% if user.is_authenticated %}
                <li><a>Hello, {{ user.username }}.</a></li>
                <li><a href="{% url 'users:logout' %}">log out</a></li>
              {% else %}
                <li><a href="{% url 'users:register' %}">register</a></li>
                <li><a href="{% url 'users:login' %}">log in</a></li>
              {% endif %}
            </ul>
          </div><!--/.nav-collapse -->
  
      </div>
    </nav>

      <div class="container">

        <div class="page-header">
            {% block header %}{% endblock header %}
        </div>
        <div>
            {% block content %}{% endblock content %}
        </div>

      </div><!-- /container -->

  </body>
</html>

learning_log/learning_log/learning_logs/templates/learning_logs/edit_entry.html
{% extends "learning_logs/base.html" %}
{% load bootstrap3 %}
{% block header %}
  <h2>Edit entry:</h2>
{% endblock header %}

{% block content %}

  <p>Topic: <a href="{% url 'learning_logs:topic' topic.id %}">{{ topic }}</a></p>

  <form action="{% url 'learning_logs:edit_entry' entry.id%}" method='post' class="form">
    {% csrf_token %}
    {% bootstrap_form form %}

    {% buttons %}
      <button name="submit" class="btn btn-parimary">Save changes</button>
    {% endbuttons %}
  </form>

{% endblock content %}

learning_log/learning_log/learning_logs/templates/learning_logs/index.html
{% extends "learning_logs/base.html" %}

{% block header %}
   <div class='jumbotron'>
     <h1>Track your learning.</h1>
   </div>
{% endblock header %}

{% block content %}
    <h2>
        <a href="{% url 'users:register' %}">Register an account</a>
        to make your own Learning Log, and list the topics your're learning about.
    </h2>
    <h2>
      Whenever you learn something new about a topic, make an entry summarizing what you've learned.
    </h2>
{% endblock content %}

learning_log/learning_log/learning_logs/templates/learning_logs/new_entry.html
{% extends "learning_logs/base.html" %}
{% load bootstrap3 %}

{% block header %}
    <h2>Add a new entry:</h2>
{% endblock header %}
{% block content %}

  <p>Topic: <a href="{% url 'learning_logs:topic' topic.id %}"> {{ topic }}</a></p>

  <form action="{% url 'learning_logs:new_entry' topic.id %}" method='post' class="form">
    {% csrf_token %}
    {% bootstrap_form form %}

    {% buttons %}
      <button name="submit" class="btn btn-parimary">Add entry</button>
    {% endbuttons %}
  </form>

{% endblock content %}

learning_log/learning_log/learning_logs/templates/learning_logs/new_topic.html
{% extends "learning_logs/base.html" %}
{% load bootstrap3 %}

{% block header %}
    <h2>Add a new topic:</h2>
{% endblock header %}
{% block content %}

  <form action="{% url 'learning_logs:new_topic' %}" method='post' class="form">
    {% csrf_token %}
    {% bootstrap_form form %}

    {% buttons %}
      <button name="submit" class="btn btn-parimary">Add topic</button>
    {% endbuttons %}
  </form>

{% endblock content %}

learning_log/learning_log/learning_logs/templates/learning_logs/topic.html
{% extends 'learning_logs/base.html' %}
{% block header %}
  <h2>{{ topic }}</h2>
{% endblock header %}

{% block content %}
    <a href="{% url 'learning_logs:new_entry' topic.id %}">add new entry</a>
  {% for entry in entries %}
      <div class="panel panel-defualt">
        <div class="panel-heading" >
            <h3>
                {{ entry.date_added|date:'M d, Y H:i' }}
                <small>
                    <a href="{% url 'learning_logs:edit_entry' entry.id %}">edit entry</a>
                </small>
                <small>
                    <a href="{% url 'learning_logs:delete_entry' entry.id %}">delete</a>
                </small>
            </h3>
        </div>
        <div class="panel-body">
          {{ entry.text|linebreaks }}
        </div>
      </div> <!-- panel -->
  {% empty %}
      <h3>There are no entries for this topic yet.</h3>
  {% endfor %}

{% endblock content %}

learning_log/learning_log/learning_logs/templates/learning_logs/topics.html
{% extends "learning_logs/base.html" %}
{% block header %}
  <h1>Topics</h1>
{% endblock header %}


 {% block content %}

  <ul>
    {% for topic in topics %}
        <h3>
            <a href="{% url 'learning_logs:topic' topic.id %}">{{ topic }}</a>
            <small><a href="{% url 'learning_logs:delete_topic' topic.id %}">delete</a></small>
        </h3>
    {% empty %}
      <li>No topics have been added yet.</li>
    {% endfor %}
  </ul>

  <h3><a href="{% url 'learning_logs:new_topic' %}">Add a new topic</a></h3>

{% endblock content %}

learning_log/learning_log/users/templates/users/login.html
{% extends "learning_logs/base.html" %}
{% load bootstrap3 %}

{% block header %}
    <h2>Log in to your account.</h2>
{%  endblock header %}
{% block content %}
    <form method="post" action="{% url 'users:login' %}" class="form">
        {% csrf_token %}
         {% bootstrap_form form %}

        {% buttons %}
            <button name="submit" class="btn btn-primary">Log in</button>
        {% endbuttons %}

    <input type="hidden" name="next" value="{% url 'learning_logs:index' %}" />
  </form>
{% endblock content %}

learning_log/learning_log/users/templates/users/register.html
{% extends "learning_logs/base.html" %}
{% block header %}
    <h2>Register a new account:</h2>
{% endblock header %}

{% block content %}

  <form method="post" action="{% url 'users:register' %}">
    {% csrf_token %}
    {{ form.as_p }}

    <button name="submit">register</button>
    <input type="hidden" name="next" value="{% url 'learning_logs:index' %}" />
  </form>

{% endblock content %}